### ISSUE TITLE
curl: (22) The requested URL returned error: 503 Service unavailable

### ISSUE THREAD

**Issue by therockster007** [activecm/BeaKer#22]
I used `./install_beaker.sh` to install beaker on Ubuntu 16.04 but I got the` curl: (22) The requested URL returned error: 503 Service unavailable error` and I'm not able to access kibana dashboard.

**Comment by william-stearns** [comment]
In /etc/BeaKer/env the elastic password is stored in ELASTIC_PASSWORD=password_here .  Line 171 of the BeaKer install script attempts to extract this with the command:

local es_pass=`$docker_sudo grep ELASTIC_PASSWORD "$BEAKER_CONFIG_DIR/env" | cut -d= -f2`

If the password contains an equals sign, this only extracts the section of the password between the first 2 equals signs on the line, not everything from the first equals sign over.  To fix this, use

local es_pass=`$docker_sudo grep '^ELASTIC_PASSWORD' "$BEAKER_CONFIG_DIR/env" | sed -e 's/^[^=][^=]*=//'`

**Comment by therockster007** [comment]
Thanks for the solution. But I am facing issue accessing kibana dashboard. Please find the attached error screenshot while installing beaker. 
![image](https://user-images.githubusercontent.com/41569730/91445911-5fe70180-e894-11ea-833d-06cf07687c07.png)

**Comment by Zalgo2462** [comment]
Hello, I believe the error you are experiencing may be unrelated to the error message you are seeing. We will take steps to reword the curl error message to make it clear what is really happening here. 

While loading the Kibana dashboards, it might experience an error while Kibana is still loading up.  It then gets a 5xx error and retries to load the dashboards after a short timeout. Here it looks like it was able to successfully upload the file on the second try. 

Here's a few things to check to narrow down where the problem is.

- Run `sudo ./beaker ps` to see if the elasticsearch and kibana services are running at all.
- Browse to `https://localhost:5601` to see if you can reach the kibana interface.
- Check the 'Saved Objects' page under 'Management' (the gear icon) tab on the left side for an item named "Sysmon" and an item named "Beacon Viewer".
![image](https://user-images.githubusercontent.com/761220/91494833-bcd3bf00-e876-11ea-9083-a9fb26aacbc3.png)

**Comment by therockster007** [comment]
Thank you @Zalgo2462 . I followed all your steps and got to know where i was going wrong. I was accessing the kibana with HTTP not HTTPS. After using HTTPS I was able to access kibana dashboard.  

Thank you @william-stearns and @Zalgo2462 for helping out.
